# Base configuration
permalink: /news/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true
gems:
  - jekyll-sitemap

#Prose.io editing info
repo_name: API-Usability-Testing
branch: gh-pages
#GitHub organization name *or* username
gh_org: 18F
prose_url: http://github.com/
site_url: http://18f.github.io/API-Usability-Testing
media: assets/img


# Your Programs's Name
name: API Usability Testing
subtitle: Taking Your Developer Engagement To The Next Level

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/API-Usability-Testing'

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: http://localhost:4000

# ------------------------------------------------------------------
#   Navigation
#   List links that should appear in the site sidebar here
#   "pages" is a directory to keep web content that are not posts
# ------------------------------------------------------------------
navigation:
- text: Home
  url: index.html
  internal: true
- text: Materials
  url: pages/materials.html
  internal: true
- text: FAQ
  url: pages/faq.html
  internal: true  
- text: Contact Us
  url: pages/contact_us.html
  internal: true 

